Repository IBM/ibm-user-management-operator, pull requests merged in 2024-08, with the labels that each got.

#41 UI installation with on-prem Redis
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/accountiam_controller.go
  internal/controller/util.go
  internal/resources/constant.go
  internal/resources/yamls/create_redis.go
Labels: lgtm, approved, size/XL

#43 Add account iam console url
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  internal/controller/accountiam_controller.go
  internal/resources/constant.go
  internal/resources/yamls/im_config.go
Labels: size/M, lgtm, approved

#45 Update Account IAM instance configs
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/accountiam_controller.go
  internal/resources/yamls/ui.go
Labels: size/S, lgtm, approved

#44 bump up version to 1.0.0
  Makefile
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-user-management-operator.clusterserviceversion.yaml
  make/ibm.mk
  test/e2e/e2e_test.go
  version/version.go
Labels: size/M, lgtm, approved

#46 update makefile
  Makefile
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-user-management-operator.clusterserviceversion.yaml
Labels: size/S, lgtm, approved

#47 version tag in makefile
  bundle.Dockerfile
  make/ibm.mk
Labels: size/XS, lgtm, approved

#48 Use Routes instead of Ingress to expose the service.
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/accountiam_controller.go
  internal/resources/yamls/app.go
  internal/resources/yamls/ui.go
Labels: size/L, lgtm, approved

#49 Update relatedImage and Makefile
  Makefile
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-user-management-operator.clusterserviceversion.yaml
  internal/controller/util.go
  internal/resources/yamls/app.go
  internal/resources/yamls/db_bootstrap.go
  internal/resources/yamls/im_config.go
  internal/resources/yamls/ui.go
  make/deps.mk
Labels: size/L, lgtm, approved

#50 Clean up incomplete jobs at the beginning of each reconciliation
  internal/controller/accountiam_controller.go
  internal/controller/util.go
  internal/resources/constant.go
Labels: size/L, lgtm, approved

#51 Add default client to MCPS audience
  internal/controller/accountiam_controller.go
  internal/controller/util.go
  internal/controller/utils/utils.go
  internal/resources/constant.go
Labels: lgtm, approved, size/XL

#53 add securityContext .seccompProfile field
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: size/S, lgtm, approved

#54 add vcs-ref and vcs-url to dockerfile
  Dockerfile
Labels: size/XS, lgtm, approved

#55 Remove cert rotation deployment
  internal/controller/accountiam_controller.go
  internal/resources/yamls/app.go
  internal/resources/yamls/iam_cert_rotation.go
Labels: size/L, lgtm, approved

#56 set vcs-ref and vcs-url for image build
  make/ibm.mk
Labels: size/XS, lgtm, approved

#57 Operator vcs-ref
  Dockerfile
  Makefile
Labels: size/XS, lgtm, approved

#58 Add new data into mcsp env configmap
  internal/controller/accountiam_controller.go
  internal/resources/yamls/app.go
Labels: size/M, lgtm, approved

#59 Add base_images.json to opt-in base image bump
  base_images.json
Labels: size/XS, lgtm, approved

#60 Remove dependency on IBM WebSphere Liberty operator and its CR
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  cmd/main.go
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/accountiam_controller.go
  internal/controller/utils/utils.go
  internal/resources/constant.go
  internal/resources/yamls/account_iam.go
  internal/resources/yamls/app.go
  internal/resources/yamls/im_config.go
Labels: lgtm, approved, size/XXL
