Repository IBM/ibm-user-management-operator, pull requests merged in 2024-07, with the labels that each got.

#10 Set test case and tool installation check on prow
  Makefile
  go.mod
  make/deps.mk
  make/ibm.mk
  scripts/makefile-check/check-docker-buildx.sh
  scripts/makefile-install/install-docker-buildx.sh
Labels: size/L, lgtm

#11 added database initialization job
  internal/controller/accountiam_controller.go
  internal/resources/yamls/db_bootstrap.go
  internal/resources/yamls/iam_cert_rotation.go
  internal/resources/yamls/utils_job_rbac.go
Labels: size/L, lgtm

#12 test installation on prow
  Makefile
  go.mod
  make/deps.mk
Labels: size/XS, lgtm

#14 added mcsp-im-config job manifests, no logic yet
  internal/resources/yamls/im_config.go
  internal/resources/yamls/utils_job_rbac.go
Labels: size/M

#15 Build production image and add owners file
  Makefile
  OWNERS
  bundle.Dockerfile
  bundle/manifests/ibm-account-iam-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  make/ibm.mk
Labels: size/M

#16 Build amd64 operator image only
  make/ibm.mk
Labels: size/XS, approved

#17 Configure artifactory credential
  Makefile
  make/ibm.mk
  scripts/makefile-config/artifactory_config_docker.sh
Labels: approved

#18 Update build make target
  make/ibm.mk
Labels: approved

#19 enable multi arch image build
  make/ibm.mk
  scripts/makefile-install/install-docker-buildx.sh
Labels: approved

#20 Revert "enable multi arch image build"
  make/ibm.mk
  scripts/makefile-install/install-docker-buildx.sh
Labels: size/XS, approved

#22 config MCSP and update bootstrap secret
  internal/controller/accountiam_controller.go
  internal/resources/yamls/app.go
  internal/resources/yamls/db_bootstrap.go
  internal/resources/yamls/iam_cert_rotation.go
Labels: size/S, lgtm, approved

#23 [WIP] Apply IM job
  bundle/manifests/ibm-account-iam-operator.clusterserviceversion.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/role.yaml
  internal/controller/accountiam_controller.go
  internal/resources/yamls/app.go
  internal/resources/yamls/im_config.go
Labels: size/L, do-not-merge/work-in-progress, approved

#21 Rename account iam to user management
  Makefile
  PROJECT
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-user-management-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/ibm-user-management-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  cmd/main.go
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-user-management-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/accountiam_editor_role.yaml
  config/rbac/accountiam_viewer_role.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/operator_v1alpha1_accountiam.yaml
  go.mod
  internal/controller/accountiam_controller.go
  internal/controller/accountiam_controller_test.go
  internal/controller/suite_test.go
  make/ibm.mk
  rename.py
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
Labels: size/L, approved

#25 Update version to 0.0.1 and channel to alpha for tech preview
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
Labels: size/S, lgtm, approved

#24 remove operatorgroup length check
  internal/controller/accountiam_controller.go
Labels: size/S, lgtm, approved

#28 Crds check
  cmd/main.go
  internal/controller/accountiam_controller.go
  internal/resources/constant.go
Labels: size/M, lgtm, approved

#33 added fields to bundle to conform to other cpfs
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-user-management-operator.clusterserviceversion.yaml
Labels: size/M, lgtm, approved

#29 Create and update bootstrap secret by user mgmt operator
  Makefile
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  cmd/main.go
  config/manifests/bases/ibm-user-management-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/accountiam_controller.go
  internal/resources/yamls/app.go
  internal/resources/yamls/db_bootstrap.go
  internal/resources/yamls/im_config.go
Labels: size/L, lgtm, approved

#36 skip config docker on local build
  make/ibm.mk
Labels: size/XS, lgtm, approved

#35 check platform deployment ready
  internal/controller/accountiam_controller.go
Labels: size/S, lgtm, approved

#34 Use service-ca.crt to access ca cert and verify
  internal/resources/yamls/app.go
Labels: size/XS, lgtm, approved

#26 added UI resources for deployment
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/accountiam_controller.go
  internal/controller/util.go
  internal/resources/yamls/ui.go
  make/ibm.mk
Labels: lgtm, approved, size/XL

#38 Make operandRequest for WebsphereLiberty and IM operator and ready status check
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  cmd/main.go
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/accountiam_controller.go
  internal/resources/constant.go
  internal/resources/yamls/im_config.go
  make/ibm.mk
Labels: lgtm, approved, size/XXL

#40 Patch image with env variable
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  internal/controller/accountiam_controller.go
  internal/controller/util.go
  internal/resources/yamls/app.go
  internal/resources/yamls/db_bootstrap.go
  internal/resources/yamls/im_config.go
  internal/resources/yamls/ui.go
Labels: size/M, lgtm, approved

#37 Support all deployment topologies
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  cmd/main.go
  config/manager/manager.yaml
  config/manifests/bases/ibm-user-management-operator.clusterserviceversion.yaml
  internal/controller/accountiam_controller.go
  internal/controller/utils/utils.go
Labels: size/M, lgtm, approved
