Repository IBM/ibm-user-management-operator, pull requests merged in 2024-09, with the labels that each got.

#62 restrict mcsp
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  internal/controller/accountiam_controller.go
Labels: size/L, lgtm, approved

#63 Skip updating resources
  internal/controller/accountiam_controller.go
  internal/controller/utils/utils.go
  internal/resources/constant.go
Labels: size/S, lgtm, approved

#64 remove reflect
  internal/controller/accountiam_controller.go
Labels: size/XS, lgtm, approved

#66 Implement resource hash comparison logic in reconciliation
  internal/controller/accountiam_controller.go
  internal/controller/utils/utils.go
  internal/resources/constant.go
  internal/resources/yamls/account_iam.go
  internal/resources/yamls/app.go
  internal/resources/yamls/ui.go
Labels: size/M, lgtm, approved

#68 [MCSP] hash comparison and deep merge all the resources
  internal/controller/accountiam_controller.go
  internal/controller/utils/utils.go
Labels: size/L, lgtm, approved

#69 Update certificate chain for user-mgmt operator and services
  internal/controller/accountiam_controller.go
  internal/resources/constant.go
  internal/resources/yamls/account_iam.go
  internal/resources/yamls/create_redis.go
  internal/resources/yamls/ui.go
Labels: size/L, lgtm, approved

#65 Watch all resources owned by AccountIAM CR
  cmd/main.go
  go.mod
  go.sum
  internal/controller/accountiam_controller.go
  internal/controller/utils/utils.go
Labels: size/M, lgtm, approved
