Repository IBM/ibm-user-management-operator, pull requests merged in 2025-04, with the labels that each got.

#79 fix flag to allow account iam application to start with new image
  internal/resources/yamls/app.go
Labels: size/S, lgtm, approved

#78 refactor: update issuer configuration in CommonService CR and improve waiting logic for ConfigMap update
  bundle/manifests/ibm-user-management-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/accountiam_controller.go
  make/ibm.mk
Labels: size/L, lgtm, approved

#80 Avoid the encryption keys conflict error
  internal/controller/accountiam_controller.go
  internal/resources/constant.go
Labels: size/M, lgtm, approved
